---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.global.backServiceName }}"
  labels:
    app: "{{ .Chart.Name }}"
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.global.backServicePort }}
      protocol: TCP
      targetPort: {{ .Values.containerPort }}
  selector:
    app: "{{ .Chart.Name }}"